config/routes.rb
Rails.application.routes.draw do
  resources :themes
    #board
    root 'board#index'
    get '/boards'           => 'board#index'    #전체목록
    get '/board/new'        => 'board#new'      #새로만들기     
    get '/board/:id/'       => 'board#show'     #자세히보기
    post '/boards'          => 'board#create'   
    get '/board/:id/edit'   => 'board#edit'     #수정하기
    
    put '/board/:id'        => 'board#update'   #전체 수정 -다 지우고 다시 수정
    patch '/board/:id'      => 'board#update'   #일부 수정 -일부만
    #둘 다 사용하는 이유는 가끔 patch를 지원하지 않는 브라우저가 있기 떄문이다.
    
    delete '/board/:id'     => 'board#destory'  #제거
    
    #user
    get '/users'            => 'user#index'     #Read
    get '/sign_up'          => 'user#new'       #Create
    get '/sign_in'          => 'user#sign_in'   #Login
    post '/sign_in'         => 'user#login'
    get '/logout'           => 'user#logout'    #logout
    
    post '/users'           => 'user#create'
    get '/user/:id'         => 'user#show'      #Read
    get '/user/:id/edit'    => 'user#edit'      #Update
    put '/user/:id'         => 'user#update'
    patch '/user/:id'       => 'user#update'
    
    #cafe
    get '/cafes'            =>'cafe#index'
    get '/cafe/new'         =>'cafe#new'
    post '/cafes'           =>'cafe#create'
    get '/cafe/:id'         =>'cafe#show'
    get '/cafe/:id/edit'    =>'cafe#edit'
    put '/cafe/:id'         =>'cafe#update'
    patch '/cafe/:id'       =>'cafe#update'
    
    delete '/cafe/:id'      =>'cafe#delete'
    
    
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method(:user_signed_in?)
  
  
  #현재 로그인 된 상태니?
  def user_signed_in?
      session[:name].present?
  end
  
  def authenticate_user!#!:bang 원하지 않은 액션이 일어날 수 있는 경우 !가 붙는다.
      redirect_to '/sign_in' unless user_signed_in?
  end
  
  #현재 로그인 된 사람이 누구니?
  def current_user
      #현재 로그인이 됨?
      if user_signed_in?
        #로그인이 되었다면, 누가했니?
        @current_user = User.find(session[:name])
      end
  end
end

  #

app/controllers/board_controller.rb
class BoardController < ApplicationController
  #before_action(:set_post, :only => [:show, :edit, :update, :destory])
  before_action(:set_post, only: [:show, :edit, :update, :destory])
  before_action(:authenticate_user!, except: [:index, :show])
  #before_action(:set_post, except: [:index, :new, :create])
  
  # 로그인 된 상태에서만 점속할 수 있는 페이지는? - 개발자 마음대로..
  # index, show만 로그인 하지 않은 상태에서 볼 수 있게
  # 나머지는 반드시 로그인이 필수
  
  # Read
  def index
    @posts = Post.all
    current_user
    @title = "indexxx"
  end

  def show
  end

  def new
    
  end
  
  def create
    post = #new와 save를 한꺼번에 진행하는 create 메서드 이다.
      Post.create(post_params)
    # post.title=params[:title]
    # post.contents=params[:contents]
    # post.user_id = current_user.id
    # post.save
    #post를 등록할 때 이 글을 작성한 사람은 현재 로그인한 유저
    puts "result"
    p post_params
    puts "end--------"
    redirect_to "/board/#{post.id}"
  end
  

  def edit
  end
  
  def update
    @post.update(post_params)
    #원래 있던 내용물을 바로 update 시키므로 save가 불필요하다.
    redirect_to "/board/#{post.id}"
  end
  
  def destory
    @post.destroy
    
    redirect_to "/boards"
  end
  
  
  
  private #이 밑으로는 외부에서 접근 불가
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params #parameter
    {title: params[:title], contents: params[:contents], user_id: current_user.id}
  end
  
  
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
    
    def index
        @cafes = Cafe.all
    end
    
    def show
        @cafe = Cafe.find(params[:id])
    end
    
    def new
        
    end
    
    def create
        cafe = Cafe.new
        cafe.title = params[:title]
        cafe.description = params[:description]
        cafe.save
        
        redirect_to "/cafe/#{cafe.id}"
    end
    
    def edit
        @cafe = Cafe.find(params[:id])
    end
    
    def update
        cafe = Cafe.find(params[:id])
        cafe.description = params[:description]
        cafe.save
        
        redirect_to "/cafe/#{cafe.id}"
        
    end
    
    def delete
        cafe = Cafe.find(params[:id])
        cafe.destroy
        
        redirect_to "cafes"
    end
        
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:title, :contents, :text)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def index
        @users = User.all
        @current_user = User.find(session[:name]) if session[:name]
        
        
        
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def new
    end
    
    def create
        user = User.new
        user.name = params[:name]
        user.password = params[:password]
        user.ip_address = request.ip
        user.save
        
        redirect_to "/user/#{user.id}"
        
    end
    
    def edit
        @user = User.find(params[:id])
        
    end
    
    def update
        user = User.find(params[:id])
        user.name = params[:name]
        user.password = params[:password]
        user.ip_address = request.ip
        user.save
        
        redirect_to "/users"
    end    
    
    def sign_in
        #Login 여부 확인
        #만일, Login 되어있다면 다시 index로....
    end
    
    def login
        #유저가 입력한 ID, PW를 바탕으로
        #실제로 Login이 이루어 지는 곳
        id = params[:name]
        pw = params[:password]
        
        user = User.find_by_name(id) #만약 데이터를 찾지 못했다면, nil값이 된다.
        
        if !user.nil? and user.password.eql?(pw)
            #아이디가 존재하고 그 비밀번호가 일치할 때.
            session[:name] = user.id
            flash[:success] = "로그인 성공"
            redirect_to '/users'
        else
            flash[:error] = "가입된 유저가 아니거나, 비밀번호가 틀립니다."
            redirect_to "/sign_in"
        end
    end
    
    def logout
        session.delete(:name)
        flash[:success] = "성공적으로 로그아웃 하였습니다."
        redirect_to "/users"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/board/_ad.html.erb
<p>_ad</p>
<h2>매주 금요일은 치킨!</h2>

app/views/board/_article.html.erb
<h1>오늘 점심 메뉴 맛이 없어</h1>
<hr>
<p>오늘 멀티캠퍼스의 점심 메뉴가 맛이 없어서 학생들에게 큰 충격을 주고있다.
많은 학생들이 메뉴에 불만을 표하며 영민짱에게 점심쏘를 요구하고있다. 영민짱은
 맛없는 점심을 책임지기 위해 최선을 다하겠다는 애매한 답변만 남겼고 같은 반의 학생들은
 분명하게 말하라고 시위를 하고있다.</p>

app/views/board/_form.html.erb
<form>
    <input type ="text">
    <input type = "submit">
</form>

app/views/board/_ranking.html.erb
<p> <%= title %></p>
<p>1. 황교익</p>
<p>2. 황교익</p>
<p>3. 황교익</p>
<p>4. 황교익</p>
<p>5. 황교익</p>
<p>6. 황교익</p>
<p>7. 황교익</p>
<p>8. 황교익</p>
<p>9. 황교익</p>
<p>10. 황교익</p>

app/views/board/edit.html.erb
<%= form_tag("/board/#{@post.id}" , method: 'patch') do %>
    <%= text_field_tag(:title, @post.title) %>
    <%= text_area_tag(:contents, @post.contents) %>
    <%= submit_tag("수정하기")%>
<%end%>

app/views/board/index.html.erb
<div>
    <ul class="list-group">
        <% @posts.each do |post| %>
            <a class = "list-group-item" href="/board/<%=post.id%>"><%=post.title%> </a>
        <%end%>
    </ul>
    
</div>
<hr>
<%= link_to "새글쓰기", "/board/new"%>

<%= render "ranking" ,title: @title%>
<%= render "article" %>
    

app/views/board/new.html.erb
<%= form_tag('/boards', method: 'POST' ) do %>
    <%= text_field_tag(:title) %>
    <%= text_area_tag(:contents) %>
    <%= submit_tag("작성하기")%>
<%end%>

app/views/board/show.html.erb
<div class="alert alert-success">
    <h2 class = "alert-heading"><%= @post.title%></h2><br>
    <p><%=@post.contents%></p>
    <hr>
<small>작성자: <%= @post.user_id%></small>
</div>


<%= link_to "목록", "/" %>
<%= link_to "수정", "/board/#{@post.id}/edit" %>
<%= link_to "삭제", "/board/#{@post.id}" , method: "delete"%>

app/views/cafe/edit.html.erb
<%=form_tag("/cafe/#{@cafe.id}", method: "PATCH") do%>
    <%=text_field_tag(:title, @cafe.title)%>
    <%=text_field_tag(:description, @cafe.description)%>
    <%=submit_tag("수정")%>
<%end%>

app/views/cafe/index.html.erb
<ul>
    <%@cafes.each do |cafe|%>
        <li><%= link_to cafe.title, "/cafe/#{cafe.id}"%></li>
    <%end%>
</ul>
<%= link_to "카페 생성", "/cafe/new"%>

app/views/cafe/new.html.erb
<%=form_tag("/cafes", method: "POST") do%>
    <%=text_field_tag(:title)%>
    <%=text_field_tag(:description)%>
    <%=submit_tag("생성")%>
<%end%>

app/views/cafe/show.html.erb
<h1><%=@cafe.title%></h1>
<p><%=@cafe.description%></p>
<%=link_to "목록", "/cafes"%>
<%=link_to "수정", "/cafe/#{@cafe.id}/edit"%>
<%=link_to "삭제", "/cafe/#{@cafe.id}", method: "delete"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaumCafe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <div class="container">
      <% if @current_user.nil? %>
        <p>현재 로그인된 유저가 없습니다.</p>
        <%= link_to "로그인", "/sign_in" %>
      <% else %>
        <p>현재 로그인 된 유저: <%= @current_user.name %></p>
        <%= link_to "로그아웃", "/logout"%>
      <% end %>
      <hr>
    </div>
    
    <% flash.each do |k, v| %>
      <p><%= v %></p>
    <%end%>
    
    

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/themes/_form.html.erb
<%= form_for(theme) do |f| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :contents %>
    <%= f.text_field :contents %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.title %></td>
        <td><%= theme.contents %></td>
        <td><%= theme.text %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @theme.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @theme.contents %>
</p>

<p>
  <strong>Text:</strong>
  <%= @theme.text %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>

app/views/user/edit.html.erb
<%=form_tag("/user/#{@user.id}", method: "PATCH") do%>
    <%=text_field_tag(:name, @user.name, readonly: true)%>
    <%=password_field_tag(:password, @user.password)%>
    <%=submit_tag("수정하기")%>
<%end%>

app/views/user/index.html.erb
<div class="alert ">
    <ul class= "list-group">
        <%@users.each do |user|%>

            <%= link_to user.name, "/user/#{user.id}", class: "list-group-item" %>

        <%end%>
    </ul>
</div>
<%= link_to "회원가입", "/sign_up"%>

<!--<table style="height: 150px">-->
<!--    <tr style="height: 65px">-->
<!--        <td rowspan="3" style="font-size: 150px; vertical-align: middle;">-->
<!--            M-->
<!--        </td>-->
<!--        <td style="font-size: 25px; vertical-align: bottom;">-->
<!--            <strong>atching</strong>-->
<!--        </td>-->
<!--    </tr>-->
<!--    <tr style="font-size: 25px; height: 30px;">-->
<!--        <td><strong>entoring</strong></td>-->
<!--    </tr>-->
<!--    <tr style="font-size: 25px; height: 55px; vertical-align: top;">-->
<!--        <td><strong>ingling</strong></td>-->
<!--    </tr>-->
<!--</table>-->

app/views/user/new.html.erb
<%=form_tag("/users", method: "POST") do%>
    <%=text_field_tag(:name)%>
    <%=password_field_tag(:password)%>
    <%=submit_tag("가입하기")%>
<%end%>

app/views/user/show.html.erb
<h1><%= @user.name%></h1>
최종 접속 아이피: <p><%=@user.ip_address%></p>
<hr>
<ul class= "list-group">
    <% @user.posts.each do |post|%>
        <%= link_to post.title, "/board/#{post.id}", class: "list-group-item" %>
    <% end %>
</ul>
<hr>

<%= link_to "목록", "/users"%>
<%= link_to "수정", "/user/#{@user.id}/edit"%>

app/views/user/sign_in.html.erb
<%=form_tag do%>
    <%=text_field_tag(:name)%>
    <%=password_field_tag(:password)%>
    <%=submit_tag("로그인")%>
<%end%>
<%= render '/board/ad' %>